### ISSUE TITLE
Chore: update to use migrated functions from solvis/issues/37

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis-graphql-api#51]
When  https://github.com/GNS-Science/solvis/issues/37 is closed and new solvis is released...
then
 - [x] update to new solvis release
 - [x] convert local  functions into wrappers for their solvis counterparts

**Comment by DrCuriosity** [comment]
Hi @chrisbc,

Have refactored to use the pre-release `solvis-0.12.0-alpha.1` version of Solvis:
```shell
poetry run pip install git+https://github.com/GNS-Science/solvis@pre-release --no-deps
```

Commit: https://github.com/GNS-Science/solvis-graphql-api/commit/22b71b391ecf78e1616fd15f8036840f53e9ea34

Outstanding things:
- It's targeting the pre-release branch. Could we maybe do an official 0.12.0 release on the Solvis side to simplify things?
- Will need to redo the Poetry config, rather than pulling it in with pip
- I think I might need to do some dependency massaging work on `solvis-store` to ensure the updated `nzshm-model` version is compatible, too
